# All numbers is True, except zero(Todos los números son verdaderos, excepto el cero.)
print(bool(15))
print(bool(20))
print(bool(0))
# Empty string is False (La cadena vacía es falsa)
print(bool("hello")) 
print(bool(""))
# Empty sequence is False (La secuencia vacía es falsa)
print(bool([1, 2, 3]))
print(bool([]))